objects/Deployment_Flow__c.object
<CustomObject>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Epic__c.object
<CustomObject>
    <fields>
        <fullName>Epic_Title__c</fullName>
        <label>Epic Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Epic</label>
    <nameField>
        <displayFormat>E{0000000}</displayFormat>
        <label>Epic Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Promoted_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promoted User Stories</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Promotions</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Create_Full_Permission_Sets_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you wish to move added permission sets to a Full Permission Sets deployment step.  This will remove them from the Metadata deployment step.</inlineHelpText>
        <label>Create Full Permission Sets Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Full_Profiles_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you wish to move added profiles to a Full Profiles deployment step.  This will remove them from the Metadata deployment step.</inlineHelpText>
        <label>Create Full Profiles Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The credential to the Destination Environment that should be used when creating a deployment. This may be auto-populated, if left blank, based on the project&apos;s deployment flow if you are the owner of an Org Credential to the Destination Environment.</inlineHelpText>
        <label>Destination Org Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.Destination_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Promotions (Destination Org Credential)</relationshipLabel>
        <relationshipName>Promotions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will provide the ability to deploy User Stories within a Release.</description>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Deployment_Complete_email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Deployment Complete email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The credential to the Source Environment that should be used when creating a deployment. This may be auto-populated, if left blank, based on the project&apos;s deployment flow if you are the owner of an Org Credential to the Source Environment.</inlineHelpText>
        <label>Source Org Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.Source_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Promotions (Source Org Credential)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>Epic__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promote_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promote Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PromoteChangesExtension.cls
public with sharing class PromoteChangesExtension {
    public Promotion__c promotion {get;set;}
    public List<Schema.FieldSetMember> promotionRelatedList {get;set;}
    
    public List<userStoryWrapper> userStories {get;set;}
    public List<promotedStoryWrapper> promotedWrappedStories {get;set;}
    public Set<Id> promotedIdsSet {get;set;}
    public ApexPages.Standardcontroller controller {get;set;}
    public Boolean renderTable_userStories {get;set;}
    public Boolean renderTable_promotions {get;set;}
    public Boolean renderStep1 {get;set;}
    public Boolean renderBtnPromote {get;set;}
    public boolean enableCreateDeploymentButton {get;set;}
    public String promotedUserStoryIds {get;set;}

    public static final String[] PROMOTION_FIELDS = new String[] {'Id','Name','Project__c','Create_Full_Permission_Sets_Step__c','Create_Full_Profiles_Step__c','Destination_Environment__c','Source_Environment__c','Source_Org_Credential__c', 'Destination_Org_Credential__c', 'Project__r.Deployment_Flow__c','Send_Deployment_Complete_email__c', 'Release__c'};
    
    public PromoteChangesExtension(ApexPages.StandardController stdController) {
        promotedIdsSet = new Set<Id>();
        renderTable_promotions = false;
        renderTable_userStories = false;
        renderBtnPromote = false;
        renderStep1 = true;
        controller = stdController;
        if (!Test.isRunningTest())stdController.addFields(PROMOTION_FIELDS);
        this.promotion = (Promotion__c)stdController.getRecord();
        if(this.promotion == null){
            this.promotion = new Promotion__c();
        }
        promotionRelatedList = SObjectType.User_Story__c.FieldSets.PromotionRelatedList.getFields();
        refreshTables();
    }
    public void refreshTables(){
        promotedIdsSet = new Set<Id>();
        promotedWrappedStories = getPromotedUserStories();
        userStories = listUserStories();
    }
    public void gotoAddUserStories(){
        listUserStories();
    }
    public List<promotedStoryWrapper> getPromotedUserStories(){
        promotedWrappedStories = new List<promotedStoryWrapper>();
        String queryFields = '';
        for(Schema.FieldSetMember f : SObjectType.User_Story__c.FieldSets.PromotionRelatedList.getFields()) {
            queryFields += ', User_Story__r.' + f.getFieldPath();
        }
        List<Promoted_User_Story__c> tmp =  Database.query(' SELECT Id, User_Story__c ' + queryFields + ' FROM Promoted_User_Story__c WHERE Promotion__c = \'' + promotion.Id + '\'');
            
            //[select Id, User_Story__c, User_Story__r.Name, User_Story__r.Status__c, User_Story__r.User_Story_Title__c , User_Story__r.Epic__c, User_Story__r.Epic__r.Epic_Title__c, Promotion__c from Promoted_User_Story__c where Promotion__c=:promotion.Id];
        for(Promoted_User_Story__c pus : tmp){
            promotedWrappedStories.add(new promotedStoryWrapper(false, pus));
            promotedIdsSet.add(pus.User_Story__c);
        }
        if(promotedWrappedStories.size()==0){
            gotoAddUserStories();
        }
        enableCreateDeploymentButton = promotedIdsSet.size()>0;
        updatePromotedIdSetToString();
        return promotedWrappedStories;
    }
    public List<userStoryWrapper> listUserStories(){
        userStories = new List<userStoryWrapper>();
        List<User_Story__c> LusProject = new List<User_Story__c>();
        List<User_Story__c> LusRelease = new List<User_Story__c>();
        String queryFields = '';
        for(Schema.FieldSetMember f : SObjectType.User_Story__c.FieldSets.PromotionRelatedList.getFields()) {
            queryFields += ',' + f.getFieldPath();
        }

        if (promotion.Project__c != null) {   
            
            LusProject = Database.query(' SELECT Id ' + queryFields + ' FROM User_Story__c WHERE Promote_Change__c=true ' + 
                             ' AND Environment__c = \'' + promotion.Source_Environment__c + '\'' + 
                             ' AND Project__c = \'' + promotion.Project__c + '\'');
            
        	for(User_Story__c us : LusProject) {
                if(!promotedIdsSet.contains(us.Id)) {
                    userStories.add(new userStoryWrapper(false, us));
                    renderTable_userStories = true; 
                }
            }
        }
        else if (promotion.Release__c != null ) {
            
            LusRelease = Database.query(' SELECT Id ' + queryFields + ' FROM User_Story__c WHERE Promote_Change__c=true ' + 
                             ' AND Environment__c = \'' + promotion.Source_Environment__c + '\'' + 
                             ' AND Release__c = \'' + promotion.Release__c + '\'');
            
            for(User_Story__c us : LusRelease) {             
                if(!promotedIdsSet.contains(us.Id)) {
                    userStories.add(new userStoryWrapper(false, us));
                    renderTable_userStories = true; 
                }
            }
        }
    
        return userStories;
    }
    public void removeSelectedUserStories(){
        List<Promoted_User_Story__c> removals = new List<Promoted_User_Story__c>();
        for(promotedStoryWrapper pus : promotedWrappedStories){
            if(pus.selected)removals.add(new Promoted_User_Story__c(Id=pus.promotedUS.Id));
        }
        delete removals;
        refreshTables();
    }
    public void addStoriesToPromotion(){

        // check if there is any userStories
        if( userStories == null || userStories.isEmpty()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.NO_USER_STORIES_TO_PROMOTE));
            return;
        }

        Integer selcount = 0;
        List<Promoted_User_Story__c> promotedStories = new List<Promoted_User_Story__c>();
        for(userStoryWrapper usw : userStories){
            if(usw.selected==true)selcount++;
        }
        if(selcount == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.NO_USER_STORIES_TO_PROMOTE));
            return;
        }

        for(userStoryWrapper usw : userStories){
            if(usw.selected==true){
                selcount++;
                if(!promotedIdsSet.contains(usw.userStory.Id)){
                    promotedIdsSet.add(usw.userStory.Id);
                    String userStoryTitle = (!String.isBlank(usw.userStory.User_Story_Title__c))?usw.userStory.User_Story_Title__c:'';
                    if(userStoryTitle.length() > 80)userStoryTitle = userStoryTitle.left(80); 
                    promotedStories.add(new Promoted_User_Story__c(Name=userStoryTitle, User_Story__c=usw.userStory.Id, Promotion__c=promotion.Id));
                }
            }
        }
        insert promotedStories;
        refreshTables();
    }
    public void updatePromotedIdSetToString(){
        promotedUserStoryIds = '';
        for(String s : promotedIdsSet){
            promotedUserStoryIds += (promotedUserStoryIds==''?'':',')+s;
        }
    }
    public class promotedStoryWrapper{
        public boolean selected {get;set;}
        public Promoted_User_Story__c promotedUS {get;set;}
        public promotedStoryWrapper(boolean b, Promoted_User_Story__c pus){
            this.selected = b;
            this.promotedUS = pus;
        }
    }
    public class userStoryWrapper{
        public boolean selected {get;set;}
        public User_Story__c userStory {get;set;}
        public userStoryWrapper(boolean b, User_Story__c us){
            this.selected = b;
            this.userStory = us;
        }
    }
}