objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Branch_Management_Coordinates__c</fullName>
        <description>This field is used to store the Branch Management Step locations of each box. This field should not be added to the page layout.</description>
        <label>Branch Management Coordinates</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Flow_Step_Coordinates__c</fullName>
        <description>This field is used to store the Deployment Flow Step locations of each box. This field should not be added to the page layout.</description>
        <label>Flow Step Coordinates</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Branch__c</fullName>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manage_Branches__c</fullName>
        <formula>HYPERLINK(&apos;/apex/&apos;&amp;
IF($Setup.Settings__c.Namespace__c=&apos;none&apos;,&apos;&apos;,
  IF(isblank($Setup.Settings__c.Namespace__c),&apos;copado__&apos;,$Setup.Settings__c.Namespace__c)
)&amp;&apos;BranchManagement?id=&apos;&amp;Id, &apos;Manage Branches&apos;, &apos;_blank&apos;)</formula>
        <label>Manage Branches</label>
        <type>Text</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Automatically_Merge_and_Deploy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatically Merge and Deploy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Level__c</fullName>
        <inlineHelpText>Test Level must be set to &quot;Run Local Tests&quot;</inlineHelpText>
        <label>Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Test Run</fullName>
                </value>
                <value>
                    <fullName>Run Specified Tests</fullName>
                </value>
                <value>
                    <fullName>Run Local Tests</fullName>
                    <default>true</default>
                    <label>Run Local Tests</label>
                </value>
                <value>
                    <fullName>Run All Tests In Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeploymentFlowExtension.cls
public class DeploymentFlowExtension {
    public Deployment_Flow__c obj {get;set;}
    public Environment__c finalDestination {get;set;}
    public List<Deployment_Flow_Step__c> steps {get;set;}
    public class GraphNone {
    	Id uid;
        String srcBranch;
        Id srcEnvId;
        Id nextEnvId;
        GraphNone nextEnv; // can be null, only for the last node;
    }
    public Map<Id,GraphNone> envNodes {get;set;}
    
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public DeploymentFlowExtension(ApexPages.StandardController stdController) {
        steps = new List<Deployment_Flow_Step__c>();
        envNodes = new Map<Id,GraphNone>();
        this.obj = (Deployment_Flow__c)stdController.getRecord();
        if(this.obj!=null && this.obj.Id!=null) {
            this.obj = [SELECT Active__c,Branch_Management_Coordinates__c,Flow_Step_Coordinates__c,Git_Repository__c,Id,Main_Branch__c,Manage_Branches__c,Name,
                    (SELECT Id,Name,Test_Level__c,Automatically_Merge_and_Deploy__c,Deployment_Flow__c,
                     Source_Environment__c, Source_Environment__r.Name, Branch__c,
                     Destination_Environment__c, Destination_Environment__r.Name
                     FROM Deployment_Flow_Steps__r ORDER BY Destination_Environment__r.Name, Source_Environment__r.Name)
                FROM Deployment_Flow__c WHERE Id = :this.obj.Id ];
        }
        System.debug('obj='+obj);
        System.debug('# of steps '+obj.Deployment_Flow_Steps__r.size());
        steps.addAll(obj.Deployment_Flow_Steps__r);

       	// prepare the last step, a virtual step, since no "connection" record exists.
        Deployment_Flow_Step__c lastStep = new Deployment_Flow_Step__c();
        lastStep.Id = null;
        lastStep.Branch__c = obj.Main_Branch__c;
        for(Deployment_Flow_Step__c s : obj.Deployment_Flow_Steps__r) {
            GraphNone g = new GraphNone();
            g.uid = s.Id;
            g.srcEnvId = s.Source_Environment__c;
            g.srcBranch = s.Branch__c;
            g.nextEnvId = s.Destination_Environment__c;
            envNodes.put(s.Source_Environment__c, g);
            
            if(s.Branch__c == obj.Main_Branch__c) {
            	lastStep.Destination_Environment__r = s.Source_Environment__r;
                System.debug('heyy '+lastStep);
            }
        }
        steps.add(lastStep);
        
        for(GraphNone g : envNodes.values()) {
            if(envNodes.containsKey(g.nextEnvId)) {
                g.nextEnv = envNodes.get(g.nextEnvId);
            }else{
                // last node.
            }
        }
    }

    public String getJsonNodes() {
        return JSON.serializePretty(envNodes);
    }

    public String getJsonDeploymentFlow() {
        return JSON.serializePretty(obj);
    }
    public String getJsonGitStatusMap() {
        // Retrieve all the attachments of the deployment flow and its steps.
		List<Id> allParentIds = new List<Id>(new Map<Id, SObject>(obj.Deployment_Flow_Steps__r).keySet());
        allParentIds.add(obj.Id);
        System.debug('allParentIds='+allParentIds);
        Map<Id,Object> GitStatusMap = new Map<Id,Object>();
        List<Attachment> atts = [SELECT ParentId, Body FROM Attachment WHERE ParentId in :allParentIds AND Name='result.json'];
        for(Attachment a : atts)
            GitStatusMap.put(a.ParentId, JSON.deserializeUntyped(a.Body.toString()));
        return JSON.serializePretty(GitStatusMap);
    }
}