objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Namespace__c</fullName>
        <inlineHelpText>If you&apos;re developing managed packages, this will help you to write only one version of the pre/post Apex Code in Selenium Test Suites. Copado will replace any &quot;{!NS}&quot; text with this value.</inlineHelpText>
        <label>Namespace</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environmental_Variable__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipName>Environmental_Variables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Environment Variable</label>
    <nameField>
        <label>Environment Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environment Variables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Selenium_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Device_Screen_Size__c</fullName>
        <description>Display Size for Windows/Mac platforms</description>
        <inlineHelpText>Display Size for Windows/Mac platforms. E.G. Saucelabs with Windows only supports small size ( &lt; 1280x1024 )</inlineHelpText>
        <label>Device Screen Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Big screen</fullName>
                </value>
                <value>
                    <fullName>Medium screen</fullName>
                    <default>true</default>
                    <label>Medium screen</label>
                </value>
                <value>
                    <fullName>Small screen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sauce Labs</fullName>
                </value>
                <value>
                    <fullName>Browser Stack</fullName>
                </value>
                <value>
                    <fullName>Custom/Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_Platforms__c</fullName>
        <description>Used by Copado to store the selected platforms to be tested in JSON format.</description>
        <label>Selected Platforms</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Webdriver_Proxy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables Saucelabs Connect or Browserstack Local Testing</description>
        <inlineHelpText>Use a local proxy to access an org behind a VPN? This enables Saucelabs Connect or Browserstack Local Testing.</inlineHelpText>
        <label>Webdriver Proxy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Webdriver_URL__c</fullName>
        <inlineHelpText>Eg for Browserstack:
http://USER:TOKEN@hub.browserstack.com:80/wd/hub

Eg for Saucelabs:
http://USER:TOKEN@ondemand.saucelabs.com:80/wd/hub/</inlineHelpText>
        <label>Webdriver URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Selenium Settings</label>
    <nameField>
        <label>Selenium Test Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Case__c.object
<CustomObject>
    <label>Selenium Test Case</label>
    <nameField>
        <label>Selenium Test Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Group__c.object
<CustomObject>
    <fields>
        <fullName>Selenium_Settings__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>All tests runs belonging to this Test Group will use these Selenium Settings.</inlineHelpText>
        <label>Selenium Settings</label>
        <referenceTo>Selenium_Settings__c</referenceTo>
        <relationshipLabel>Selenium Test Groups</relationshipLabel>
        <relationshipName>Selenium_Test_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Selenium Test Group</label>
    <nameField>
        <label>Selenium Test Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Run__c.object
<CustomObject>
    <fields>
        <fullName>Base_URL__c</fullName>
        <description>Optional Base URL where this test will be run, if Org Credentials are not specified.</description>
        <inlineHelpText>Optional Base URL where this test will be run, if Org Credentials are not specified.</inlineHelpText>
        <label>Base URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Batch_No__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Batch No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <formula>Org_Credential__r.Environment__r.Name</formula>
        <label>Environment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Copado will log in to Salesforce using this Org Credential.  There is no need to record username and password of the Salesforce login page.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>SeleniumTestRuns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selenium_Settings__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Copado will run the Test Suites for each of the selected Platforms in these Settings.</inlineHelpText>
        <label>Selenium Settings</label>
        <referenceTo>Selenium_Settings__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selenium_Test_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field should not be populated.  The value is automatically maintained.</inlineHelpText>
        <label>Selenium Test Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Selenium_Test_Group__c.Manage_Test_Runs_manually__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Selenium_Test_Group__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selenium_Test_Suite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Selenium Test Suite</label>
        <referenceTo>Selenium_Test_Suite__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Selenium Test Run</label>
    <nameField>
        <label>Selenium Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Suite__c.object
<CustomObject>
    <fields>
        <fullName>Apex_code_after_test__c</fullName>
        <inlineHelpText>Optional Apex code to execute after running this test suite. You can use variable {!NS} to be replaced with the Namespace for the running Environment.</inlineHelpText>
        <label>Apex code after test</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Apex_code_before_test__c</fullName>
        <inlineHelpText>Optional Apex code to execute before running this test suite.  It can be used to clean up or create data. You can use variable {!NS} to be replaced with the Namespace for the running Environment.</inlineHelpText>
        <label>Apex code before test</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Selenium Test Suite</label>
    <nameField>
        <label>Selenium Test Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SeleniumTestCaseRunData.cls
@RestResource(urlMapping='/SeleniumTestCaseRunData')
global with sharing class SeleniumTestCaseRunData {

    global class RunVar {
        public RunVar(String n, String v) { Name=n; Value=v; }
        public String Name;
        public String Value;
    }
    
    global class RunTestCaseAndData {
        public RunTestCaseAndData(Id i, String s, String d, String dn) { id=i; src=s; data=d; dataName=dn; }
        public Id id;
        public String src;
        public String data;
        public String dataName;
    }
    
    global class RunMain {
        public Id Run_Id;
        public String Run_Name;
        public String Run_Base_URL;
        public integer Run_Batch_No;
        public String Run_Namespace;
        public String Run_Org_Credential;
        public String Settings_Name;
        public String Settings_Provider;
        public String Settings_Selected_Platforms;
        public boolean Settings_Webdriver_Proxy;
        public String Settings_Webdriver_URL;
        public String Suite_Apex_code_after_test;
        public String Suite_Apex_code_before_test;
        public String Suite_Id;
        public List<RunVar> global_vars;
        public String login_url;
        public List<RunTestCaseAndData> testcases;
        public String run_unique_id;
    }
    
    @HttpGet
 	global static RunMain testCaseLoadAll() {
        RestResponse res = RestContext.response;
        res.addHeader('Access-Control-Allow-Origin', '*');
        res.addHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE');
        res.addHeader('Access-Control-Allow-Headers', 'Content-Type,Authorization');
		res.addHeader('Content-Type', 'application/json');

        String testRunId = RestContext.request.params.get('id');
        RunMain rm = new RunMain();
        
        Selenium_Test_Run__c r = [SELECT
            Id,
            Name,
            Batch_No__c,
            Org_Credential__c,
            Org_Credential__r.Environment__r.Namespace__c,
            Org_Credential__r.Environment__r.Id,
            Base_URL__c,
            Selenium_Settings__r.Name,
            Selenium_Settings__r.Selected_Platforms__c,
            Selenium_Settings__r.Provider__c,
            Selenium_Settings__r.Webdriver_Proxy__c,
            Selenium_Settings__r.Webdriver_URL__c,
            Selenium_Settings__r.Device_Screen_Size__c,
            Selenium_Test_Suite__r.Id,
            Selenium_Test_Suite__r.Apex_code_before_test__c,
            Selenium_Test_Suite__r.Apex_code_after_test__c,
            Selenium_Test_Group__r.Id
            FROM Selenium_Test_Run__c
            WHERE Id=:testRunId];
        
        rm.Run_Id = r.Id ;
        rm.Run_Name = r.Name ;
        rm.Run_Base_URL = r.Base_URL__c ;
        rm.Run_Batch_No = (integer)r.Batch_No__c ;
        rm.Run_Namespace = r.Org_Credential__r.Environment__r.Namespace__c ;
        rm.Run_Namespace = rm.Run_Namespace==null?'':rm.Run_Namespace;
        rm.Run_Org_Credential = r.Org_Credential__c ;
        rm.Settings_Name = r.Selenium_Settings__r.Name ;
        rm.Settings_Provider = r.Selenium_Settings__r.Provider__c;
        rm.Settings_Selected_Platforms = r.Selenium_Settings__r.Selected_Platforms__c ;
        rm.Settings_Webdriver_Proxy = r.Selenium_Settings__r.Webdriver_Proxy__c ;
        rm.Settings_Webdriver_URL = r.Selenium_Settings__r.Webdriver_URL__c ;
        rm.Suite_Apex_code_after_test = r.Selenium_Test_Suite__r.Apex_code_after_test__c ;
        rm.Suite_Apex_code_before_test = r.Selenium_Test_Suite__r.Apex_code_before_test__c ;
        rm.Suite_Id = r.Selenium_Test_Suite__r.Id ;
        if(String.isNotBlank(rm.Run_Base_URL)) {
            rm.Run_Namespace = null;
            rm.Run_Org_Credential = null;
        }

        List<Selenium_Test_Case_Per_Suite__c> tcs = [SELECT Id, Selenium_Test_Case__r.Id, Selenium_Test_Case__r.Name,
            Test_Dataset_Name__c
            FROM Selenium_Test_Case_Per_Suite__c
            WHERE Selenium_Test_Suite__c = :rm.Suite_Id
            ORDER BY Order__c, CreatedDate];
        
        List<Id> ids = new List<Id>();
        for(Selenium_Test_Case_Per_Suite__c t : tcs)
            ids.add(t.Selenium_Test_Case__r.Id);
		
        // note, for this to work: the testcase must be always the FIRST item, so the ORDER must be appropiate
        List<Attachment> ltc = [SELECT Id, ParentId, Name, Body FROM Attachment WHERE ParentId in :ids AND Name in ('Copado.SeleniumTestCase.json', 'Copado.SeleniumTestData.json') ORDER BY name ASC LIMIT 199];
        Map<Id,List<Attachment>> mtc = new Map<Id,List<Attachment>>();
        for(Attachment t :ltc) {
            if(!mtc.containsKey(t.parentId))
                mtc.put(t.parentId, new List<Attachment>());
            mtc.get(t.parentId).add(t);
        }
        rm.testcases = new List<RunTestCaseAndData>();
        List<Id> testCasesRequiringLocators = new List<Id>();
        for(Selenium_Test_Case_Per_Suite__c t : tcs) {
            if(mtc.containsKey(t.Selenium_Test_Case__r.Id)) {
                RunTestCaseAndData cd = new RunTestCaseAndData(t.Selenium_Test_Case__r.Id, null, null, null);
                cd.src = mtc.get(t.Selenium_Test_Case__r.Id).get(0).Body.toString();
                if(cd.src.containsIgnoreCase('{!Locator.'))
                    testCasesRequiringLocators.add(cd.Id);
                if(mtc.get(t.Selenium_Test_Case__r.Id).size()>1) {
                    cd.dataName = t.Test_Dataset_Name__c;
	                cd.data = mtc.get(t.Selenium_Test_Case__r.Id).get(1).Body.toString();
                    if(cd.data.containsIgnoreCase('{!Locator.'))
                        testCasesRequiringLocators.add(cd.Id);
                }
	            rm.testcases.add( cd );
            }
        }
		
        rm.global_vars = new List<RunVar>();
        rm.run_unique_id = String.valueOf((integer)(Math.random()*9999));
        rm.global_vars.add( new RunVar('RUN_ID', rm.run_unique_id) );
        rm.global_vars.add( new RunVar('NS', rm.Run_Namespace) );
        rm.global_vars.add( new RunVar('BLANK', '') );
        
        List<Selenium_Group_Variable__c> gvars = [SELECT Id, Name, Value__c
            FROM Selenium_Group_Variable__c
            WHERE Selenium_Test_Group__c = :r.Selenium_Test_Group__r.Id];
        for(Selenium_Group_Variable__c t : gvars)
            rm.global_vars.add( new RunVar('Group.'+t.Name, t.Value__c) );
        
        List<Environmental_Variable__c> evars = [SELECT Id, Name, Value__c
            FROM Environmental_Variable__c
            WHERE Environment__c = :r.Org_Credential__r.Environment__c];
        for(Environmental_Variable__c t : evars)
            rm.global_vars.add( new RunVar('Environment.'+t.Name, t.Value__c) );
        
        if(testCasesRequiringLocators.size()>0) {
        	List<Selenium_Locator_Reference__c> ls = [SELECT Selenium_Locator__r.Locator_ID__c, Selenium_Locator__r.Locator__c
            FROM Selenium_Locator_Reference__c
            WHERE Selenium_Test_Case__c in :testCasesRequiringLocators AND Selenium_Locator__r.Locator_ID__c != NULL];
            for(Selenium_Locator_Reference__c t : ls)
                rm.global_vars.add( new RunVar('Locator.'+t.Selenium_Locator__r.Locator_ID__c, t.Selenium_Locator__r.Locator__c) );
        }

		return rm;
    }

}