objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <defaultValue>&quot;master&quot;</defaultValue>
        <inlineHelpText>the branch in the selected git repository. Usually &quot;master&quot;.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Commit_Message__c</fullName>
        <label>Commit Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Git_Backup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Snapshot</label>
        <referenceTo>Git_Backup__c</referenceTo>
        <relationshipName>Git_Org_Commits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Commits</relationshipLabel>
        <relationshipName>Git_Org_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GitCommitChangesController.cls
global with sharing class GitCommitChangesController{

	public Git_Org_Commit__c gitCommit{get;set;} 

	public String repositoryId {get;set;}
	public String snapshotId {get;set;}
	public String orgId {get;set;}
    public String userStoryId {get;set;}

	public String orgName {get;set;}
	public String repoName {get;set;}
	public String branch {get;set;}

    public Git_Backup__c gitBackup {get;set;}
    public User_Story__c userStory {get;set;}
    public boolean showSnapshotInformation{get;set;}

    public List<Schema.FieldSetMember> getFields() {
    	List<Schema.FieldSetMember> fields = SObjectType.Git_Backup__c.FieldSets.Commit_Files_Information.getFields();
        showSnapshotInformation = fields.size()>0;
        return fields;
    }
    public List<Schema.FieldSetMember> getUSFields() {
    	return SObjectType.User_Story__c.FieldSets.Commit_Files_Information.getFields();
    }
	/**
	 * constructor
	 * @return [description]
	 */
	public GitCommitChangesController() {
		// get from parameter the related snapshot
		Map<String, String> params = ApexPages.currentPage().getParameters();

		repositoryId = params.get('repoId');
		snapshotId = params.get('snapshotId');
		orgId = params.get('orgId');
        userStoryId = params.get('userStoryId');
        
        String Commit_Message = '';
        if(String.isNotEmpty(userStoryId)) {
            // get values for userStory fields and commit message
            try {
                String query = 'SELECT ';
                for(Schema.FieldSetMember f : this.getUSFields()) {
                    String fp = f.getFieldPath();
                    if(fp != 'Name') {
                        query += fp + ', ';
                    }
                }
                query += 'Name FROM User_Story__c WHERE Id =:userStoryId LIMIT 1';
                userStory = Database.query(query);
            } catch (Exception e) {
                System.debug(e);
            }
            for( User_Story__c us : [SELECT Name, User_Story_Title__c  FROM User_Story__c WHERE Id =:userStoryId]) {
	            Commit_Message = (us.Name +': ' + (String.isEmpty(us.User_Story_Title__c)?'': us.User_Story_Title__c)).left(254);
            }
        }
        
		// get values snapshot fields and subtitle
        try {
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : this.getFields()) {
                String fp = f.getFieldPath();
                if(fp != 'Git_Repository__r.Name')  {
                    query += fp + ', ';
                }
            }
            query += ' Git_Repository__r.Name FROM Git_Backup__c WHERE Id =:snapshotId LIMIT 1';
            gitBackup = Database.query(query);
        } catch (Exception e) {
            System.debug(e);
        }
        
        Git_Backup__c snapshot = [SELECT Org__r.Name, Branch__c, Git_Repository__r.Name FROM Git_Backup__c WHERE Id =:snapshotId ];
		orgName = snapshot.Org__r.Name;
		repoName = snapshot.Git_Repository__r.Name;
		branch = snapshot.Branch__c;

		// create a fake commit record
		gitCommit = new Git_Org_Commit__c(
			Git_Backup__c = snapshotId,
			Org__c = orgId,
            Commit_Message__c = Commit_Message
		); 
	}
}