objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Git_Snapshot_Permissions__c</fullName>
        <label>Git Snapshot Permissions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Allow Snapshots &amp; Commits</fullName>
                    <default>true</default>
                    <label>Allow Snapshots &amp; Commits</label>
                </value>
                <value>
                    <fullName>Allow Snapshots Only</fullName>
                </value>
                <value>
                    <fullName>Allow Commits Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EditBackupExtension.cls
public with sharing class EditBackupExtension {

    public final String STATIC_RESOURCE = 'StaticResource';

    private List<String> metadataTypes;
    public List<SelectOption> types;
    public List<SelectOption> selectedTypes{get;set;}
    public Git_Backup__c backup;
    public List<String> sel{get;set;}
    public boolean showOtherInformation{get;set;}

    public Boolean isStaticResourcesSelected {get;set;}

    
    public Settings settings {get;set;}
    
    public EditBackupExtension(ApexPages.StandardController stdController) {
        settings = new Settings();
        backup = (Git_Backup__c)stdController.getRecord();
        
        isStaticResourcesSelected = false;
        selectedTypes = new List<SelectOption>();
        sel = new List<String>();

        if(backup.Metadata_Types__c != null){
            for(String t:backup.Metadata_Types__c.split(',')){
                selectedTypes.add(new SelectOption(t,t));    
                sel.add(t);

                if(t == STATIC_RESOURCE){
                    isStaticResourcesSelected = true;
                }
            }
        }else{
            isStaticResourcesSelected = true;
        }
        sel.sort();

        showOtherInformation = SObjectType.Git_Backup__c.FieldSets.CustomFields.getFields().size()>0;
    }
    public void init(){
        
    }
    public void reRender(){
        
    }
    public List<String> getMetadataTypes(){

        return MetadataTypesHelper.getMetadataTypesByOrgId(backup.Org__c);
    
    }

    public List<SelectOption> getTypes() {

        return MetadataTypesHelper.getTypeOptionsByOrgId(backup.Org__c, sel);
    
    }

    public void setTypes(List<SelectOption> l){
        types = l;
    }

    public PageReference save(){
        backup.Metadata_Types__c = MetadataTypesHelper.joinOptions(selectedTypes);
        if(String.isNotBlank(backup.Frequency__c) && backup.Frequency__c!='None' && backup.Git_Snapshot_Permissions__c == 'Allow Commits Only'){
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,Label.COMMIT_ONLY_SNAPSHOTS_CANNOT_BE_SCHEDULED));
            return null;
        }
        upsert backup;
        return new PageReference('/'+backup.id);
    }

    /**
     * This method is a helper which refresh the OrgId when the record is new
     * Is a helper for javascript refresh call
     */
    public PageReference orgChanged(){
        
        //get the new ID 
        String OrgId = Apexpages.currentPage().getParameters().get('OrgId');
        //save to controller record
        backup.Org__c = OrgId;
        //refresh MetadataTypes using the new Id
        getMetadataTypes();
        return null;
    }

    
}