objects/Personal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object stores the personal settings for Copado</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Personal Settings</label>
</CustomObject>

classes/JsRemotingController.cls
global with sharing class JsRemotingController {
	/*
	The purpose of this class is to encapsulate various methods of Apex controller
	and make these available via Javascript Remoting.
	*/
    @RemoteAction
    global static String createAPIKey(){
        Personal_Settings__c mySettings = Personal_Settings__c.getInstance();
        if(String.isBlank(mySettings.API_Key__c)){
            DeployApi.createAPIKey();
        }
        return DeployAPI.getUserAPIKey();
    }
    
    /**
     * constructor methods. 
     */
    public JsRemotingController(ApexPages.StandardController sc) {}
    public JsRemotingController(){}
}